### ISSUE TITLE
Enchantment list is sometimes desynced

### ISSUE THREAD

**Issue by Dekamir** [MoriyaShiine/enchancement#103]
### Mod version

1.19-14

### A description of the issue

Enchantment list on some items are desync between the client and the server.

For example, Fire Aspect may be missing in a server Enchantment Table. 
To resync, one requires to load a singleplayer world, open an Enchantment Table and put the item there, rejoin the server.

This also has the chance to randomly add said enchantment, even though it's not even visible (or selected).

**Comment by MoriyaShiine** [comment]
Does this still happen in 1.20? There's a new config desync check that should apply

**Comment by Dekamir** [comment]
The specified bug here seems to be irrelevant to this mod.
It stems from this issue [here (Universal Enchants issue 75)](https://github.com/Fuzss/universalenchants/issues/75).

Sorry for the misleading bug report **:(**
