### ISSUE TITLE
Bouncy jump boost bar ignores screen safe area

### ISSUE THREAD

**Issue by Dekamir** [MoriyaShiine/enchancement#104]
### Mod version

1.19-14

### A description of the issue

![image](https://github.com/MoriyaShiine/enchancement/assets/28929300/bce1d8e4-4544-456d-b150-bdc0cfd41399)

Mods can add screen safe areas to Minecraft. This instance has BedrockIfy.

Jump Boost bar of Bouncy does not take this into account.
Enchancement may have hardcoded this position and should use relative or check where the experience bar is.

**Comment by MoriyaShiine** [comment]
Minecraft doesn't have screen safe areas, this is something Bedrockify specifically adds. Closing for the same reason that https://github.com/juancarloscp52/BedrockIfy/issues/279 exists
