### ISSUE TITLE
remapping error when trying to join server

### ISSUE THREAD

**Issue by Daybroken0** [MoriyaShiine/enchancement#106]
### Mod version

1.18-18

### A description of the issue

me and two of my friends are playing on a server with some other mods, me and one friend are working fine when joining but since adding this mod my friend gets this error:

registry remapping failed: received id map for minecraft:enchantment contains ids unknown to the receiver! -enchancement:buffet

he plays on a mac, is using curseforge for the mods and we don't know what to do.

**Comment by MoriyaShiine** [comment]
Server and client configs must match, if you haven't changed it then delete the config files and and they regenerate
