### ISSUE TITLE
Custom Enchants do not cancel eachother 

### ISSUE THREAD

**Issue by magmabits** [MoriyaShiine/enchancement#107]
### Mod version

v1.19-18

### A description of the issue

When all enchants are enabled, custom enchants (e.g: Amphibious and Strafe) do not cancel each other (aka you can get both on one piece).
![Enabled Enchants](https://github.com/MoriyaShiine/enchancement/assets/66217030/e8a67cd7-b8f1-47d2-b733-82f692f238bd)
I don't know if that is intentional or not, but there should maybe be an option to limit tools and armor to only have one custom enchant.

**Comment by MoriyaShiine** [comment]
This is intentional, turning off single enchant mode functions like how vanilla does; there are a couple specific incompatibilities like frostbite and fire aspect, but if there's no reason they shouldn't work together then they can be combined like normal
