### ISSUE TITLE
Incompatibility with Freezing Myhtic Mount mobs

### ISSUE THREAD

**Issue by dandin87** [MoriyaShiine/enchancement#11]
### Mod version

enchancement-1.18-17

### A description of the issue

java.lang.IllegalStateException: Unable to generate frozen texture for mythicmounts:courierbird_mount7.png

### Log or crash report

https://aofpaste.com/oraqatisux.yaml

**Comment by MoriyaShiine** [comment]
Mythic Mounts is closed source, so I can't actually see why this is breaking. I would suggest reporting to them.

**Comment by hashworks** [comment]
```
java.lang.IllegalStateException: Unable to generate frozen texture for mythicmounts:firebird_mount3.png
	at moriyashiine.enchancement.client.reloadlisteners.FrozenReloadListener.lambda$getTexture$0(FrozenReloadListener.java:67)
```

Basically this happens at [this line](https://github.com/MoriyaShiine/enchancement/blob/1d409f1cd4eaa6c806552a2970a51d0d1e021f1e/src/main/java/moriyashiine/enchancement/client/reloadlisteners/FrozenReloadListener.java#L67).

While it true that this might be an issue Mythic Mounts has to fix, I think it would be wise to not throw the `IllegalStateException` here and simply return the original – log an error instead and call it a day.

**Comment by dandin87** [comment]
This is also an issue with Twilight Forest Bosses or Mobs (I forgot which one, or if both). Seems I forgot to update this with that info when someone found it. And since Twilight Forest is not closed source, it will be much easier to test against.
