### ISSUE TITLE
can't join server with this mod

### ISSUE THREAD

**Issue by Fa1s3** [MoriyaShiine/enchancement#110]
### Mod version

1.19.2

### A description of the issue

whenever i try to to log onto a friend's server (on pebblehost) it displays the text in the screenshot
![mc error](https://github.com/MoriyaShiine/enchancement/assets/137194234/6b517164-20e0-4365-936b-0a49c52ac3f8)
. From the looks of it, it seems the issue is that mc doesn't recognise those specific items from the mod and after a server restart, reinstalling the mod and installing a different version of fabric it still doesn't work. The strangest part though is that it works for everyone else but me and another person which proves it's not an issue with my computer or with the server.

**Comment by MoriyaShiine** [comment]
Clone of #106 

Always check changelogs, there are multiple versions where you need to reset the config file between updates
