### ISSUE TITLE
Channeling description is inaccurate

### ISSUE THREAD

**Issue by MerchantPug** [MoriyaShiine/enchancement#116]
### Mod version

1.20-3

### A description of the issue

"Causes the Trident to summon lightning when striking a mob while it's thundering."

Enchancement allows summoning lightning without the thundering condition.

I'm unsure if this can be fixed because the game won't know whether to load Enchancement's description or Enchantment Descriptions' description. You could always reroute channeling to use a different key if necessary, but I'm unsure if that'd be too much hassle for what it's worth.

**Comment by MoriyaShiine** [comment]
Enchancement already reroutes the key if the config options are different 

see: https://github.com/MoriyaShiine/enchancement/blob/766c9722f3db9831b8956df43394617aa7ba637d/src/main/java/moriyashiine/enchancement/mixin/util/TranslatableTextContentMixin.java#L23

I'm unable to reproduce this issue and it appears to work fine with every config combination
![2023-08-03_11 57 25](https://github.com/MoriyaShiine/enchancement/assets/45156123/b4e03dec-75ba-4c12-8857-57dd53ac570e)
![2023-08-03_11 57 36](https://github.com/MoriyaShiine/enchancement/assets/45156123/3bb79d1b-fa25-4d99-86dc-cd7473c0b16a)
![2023-08-03_11 57 45](https://github.com/MoriyaShiine/enchancement/assets/45156123/2669cbbc-0bc7-4797-99bf-2c6d542494b9)
![2023-08-03_11 57 54](https://github.com/MoriyaShiine/enchancement/assets/45156123/4b19ee60-2a77-4c2a-b9de-5d39ba1133b4)

**Comment by MerchantPug** [comment]
Oh, interesting. I didn't know about this. Ty.
