### ISSUE TITLE
Crash on startup with Porting Lib

### ISSUE THREAD

**Issue by jakeismyname** [MoriyaShiine/enchancement#117]
### Mod version

1.20-5

### A description of the issue

Crash on startup when Enchancement is installed with latest version of Porting Lib (2.1.1085).

### Log or crash report

https://mclo.gs/s9pAxZr

**Comment by MoriyaShiine** [comment]
Known issue with Porting Lib. TropheusJ said they'll fix it but it couldn't hurt to make an issue on their GitHub if there isn't one already
