### ISSUE TITLE
Enchancement 1.18.2 Incompatiblility

### ISSUE THREAD

**Issue by KingEatsPants** [MoriyaShiine/enchancement#118]
### Mod version

1.18.2

### A description of the issue

In the latest 1.18.2 version of this mod, Enchancement is incompatible with geckolib. This was fixed in the 1.19 and above versions although a lot of mods I use are in 1.18.2. This small fix would help me out a lot, so could you please fix this?
![Screenshot 2023-08-06 141910](https://github.com/MoriyaShiine/enchancement/assets/141548168/e6eef6ab-2214-4db9-8756-602014c67bf4)

**Comment by MoriyaShiine** [comment]
Unfortunately I don't update old versions, but if I recall correctly, this can be fixed by downgrading Geckolib

**Comment by KingEatsPants** [comment]
Just a quick question. What version of Geckolib is Enchancement 1.18.2 compatible with? The 1.18.2 Geckolib doesn't work.
