### ISSUE TITLE
Using a grindstone to disenchant an item with a custom enchant, crashes the game.

### ISSUE THREAD

**Issue by DvidPiDev** [MoriyaShiine/enchancement#119]
### Mod version

1.19-14

### A description of the issue

If you have an item that has enchants from the mod, attempting to remove them using a grindstone crashes the game as soon as it enters one of the grindstone slots. I'm using 1.19.2.
I also have this mod on a Quilt server. The server does not crash, only the player that is trying to disenchant the item will crash.

### Log or crash report

https://gist.github.com/DvidPiDev/3e9c75e59b3f20645147e5ddd6f9587c

**Comment by MoriyaShiine** [comment]
I don't see Enchancement anywhere in that crash report. The only mods that seem to be interacting are Pollen, Mialeemisc, and Quilted Fabric Transfer API (probably part of QFAPI)

**Comment by DvidPiDev** [comment]
Alright, going to try removing those and report back. Thanks for the help!

**Comment by DvidPiDev** [comment]
Okay, looks like this was caused by "Pollen". I got rid of that but I also had to get rid of "Mannequins" (I suppose because it was relying on Pollen..?). Anyway, now the game doesn't crash and it removes the enchants successfully.
Thanks again!
