### ISSUE TITLE
Enchanting doesn't use up the XP that was configured.

### ISSUE THREAD

**Issue by DvidPiDev** [MoriyaShiine/enchancement#120]
### Mod version

1.19-14

### A description of the issue

Possible duplicate of #100
Even though it was marked as fixed, it actually doesn't appear to be.
When players enchant something with an enchanting table, (eg. book) it doesn't use any XP. I just noticed this issue when half of the server enchanted their gear with the most OP enchants at zero cost. 😆 Oh well, I guess they were lucky.

Config file: https://haste.dvidpi.eu.org/quxuruvofu.json
Any help is appreciated!

### Log or crash report

No log or crash report needed

**Comment by MoriyaShiine** [comment]
It was only fixed in 1.20.1 as I don't tend to update old versions of my mods. I may backport at some point but it's not a priority. I mentioned on my discord that I'll do it if I get paid enough, but otherwise it's too much work for too little gain :p
