### ISSUE TITLE
Brimstone not compatible with Lifesteal Mod

### ISSUE THREAD

**Issue by PrinceFeggari** [MoriyaShiine/enchancement#121]
### Mod version

1.20-5

### A description of the issue

Brimstone uses half health instead of 6 hearts it does much more. So in Lifesteal if you have 25 hearts it used 15 and only dealt 6. I killed myself faster than my target.

**Comment by MoriyaShiine** [comment]
This is intentional; it does calculations based on the user's and target's max health, not a flat amount

**Comment by PrinceFeggari** [comment]
> This is intentional; it does calculations based on the user's and target's max health, not a flat amount

Oh
