### ISSUE TITLE
Compatibility with Enchantery 1.20

### ISSUE THREAD

**Issue by lxly9** [MoriyaShiine/enchancement#124]
### Mod version

1.20-6

### A description of the issue

Enchancement and [Enchantery](https://modrinth.com/mod/enchantery) are sadly not compatible due to a bug in the enchanting table as described below. 

When using enchancement with enchantery and 'enchanting table overhaul' is off while 'single level mode' is turned on in the config, the enchanting table does not produce the described enchantments in the table. Even if books are put in chiseled bookshelves or using soul torches to influence the outcome the described enchantments are not applied and apply a 'base enchantment' (in case of armor its protection, for weapons sharpness and tools efficiency). 
It would be great if we got some compatibility between the two mods as enchancements enchantments are a game changer haha

### Log or crash report

https://gist.github.com/lxly9/de10cb7a1d7b1905cbbe1a562ba43686

**Comment by MoriyaShiine** [comment]
Enchancement removes Protection and Sharpness by default, try enabling them and seeing if it works

**Comment by lxly9** [comment]
i will try that!

**Comment by lxly9** [comment]
hmm, after testing (and falling asleep lolol) it behaves the same way still

**Comment by MoriyaShiine** [comment]
Is this still an issue? I'm not sure what to do with it lol

**Comment by lxly9** [comment]
I will check again today, I do believe it is still one but I hope not haha

**Comment by lxly9** [comment]
huh, still the same issue sadly, it appears to be scooping in the enchanting table, but when clicked on its efficency

**Comment by MoriyaShiine** [comment]
I've completely rewritten the disallowed enchantments system in the upcoming update, so I'm not sure if this will still be a problem. If it is, I'm not really sure what I would do about it
