### ISSUE TITLE
[1.19.2] Hard dependency on TooltipFix and Enchdesc

### ISSUE THREAD

**Issue by CactusDuud** [MoriyaShiine/enchancement#125]
### Mod version

1.19-14

### A description of the issue

1.19 version of Enhancement requires [TooltipFix](https://modrinth.com/mod/tooltipfix) and [Enchdesc](https://modrinth.com/mod/enchantment-descriptions), but I have [other mods](https://modrinth.com/mod/idwtialsimmoedm) that provide the same functionality. I'm pretty sure neither of those mods have features that the mod actually requires, so I'd appreciate if the dependencies were removed.

**Comment by MoriyaShiine** [comment]
Both dependencies are part of the design of the mod (tooltips are completely unreadable without tooltipfix and enchantment descriptions provides descriptions); you are free to remove them with [dependency overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides). 1.20.1 no longer requires enchantment descriptions as well, and has its own implementation that disables itself when any of the 3 big enchantment description mods are installed (or manually disable-able as usual)
