### ISSUE TITLE
Enchantment name doesn't respect single level mode option

### ISSUE THREAD

**Issue by Treetrain1** [MoriyaShiine/enchancement#126]
### Mod version

1.20-6

### A description of the issue

I have the "Single Level Mode" option set to "No", but all of my item names fail to say the level of their enchantment.

![image](https://github.com/MoriyaShiine/enchancement/assets/39657565/0ed1b665-6d67-4171-9263-b3048f014813)
![image](https://github.com/MoriyaShiine/enchancement/assets/39657565/50aaa630-8084-4a09-afdf-a21cb6f4828c)

**Comment by StitchLockwood** [comment]
I too am experiencing this issue.

**Comment by MoriyaShiine** [comment]
I'm unable to reproduce this, I'm releasing a new version soon so if it still happens on that one feel free to comment
