### ISSUE TITLE
Frostbite prevents Bosses from Bosses of Mass Destruction of dropping loot

### ISSUE THREAD

**Issue by FumpleWumper** [MoriyaShiine/enchancement#127]
### Mod version

1.20-6

### A description of the issue

Bosses from the BOMD mod are supposed to trigger an event when they die that spawns custom blocks like chests, ancient debris and shulker boxes with loot and all that. But if they turn into an ice statue due to Frostbite when they die, it stops them from triggering these events and therefore giving out any loot

**Comment by MoriyaShiine** [comment]
Bosses are immunity to freezing but it looks like bomd doesn't add to the common bosses tag; I suggest opening an issue there
