### ISSUE TITLE
Requiem Incompatibility

### ISSUE THREAD

**Issue by Eman-3600** [MoriyaShiine/enchancement#13]
### Mod version

enchancement-1.18-13.jar

### A description of the issue

Tried to play this with the latest Requiem beta (1.18.1), but trying to load a Brimstone enchanted crossbow crashes the game. Upon trying to boot the world back up, the game crashed again. The only way to recover the world was to uninstall the mod and shoot the loaded crossbow before I could load the world again with the mod installed.

### Log or crash report

[Requiem Crash.txt](https://github.com/MoriyaShiine/enchancement/files/8794601/Requiem.Crash.txt)

**Comment by LetsWin18** [comment]
same thing with me

**Comment by Eman-3600** [comment]
note that it's fixed for the 1.18.2 version

**Comment by MoriyaShiine** [comment]
Ah, that's good. Thanks for letting me know :)
