### ISSUE TITLE
Tooltip dependency on Quilt

### ISSUE THREAD

**Issue by AzraelAbaddon** [MoriyaShiine/enchancement#130]
### Mod version

1.19-14

### A description of the issue

Hi, I'm trying to use this mod on Quilt for 1.19.2 and it keeps crashing saying it needs tooltipfix.

Problem I'm running into is that Tooltipfix doesn't work with quilt whilst Enchancement does, and since the override is for fabric I'm unsure if it still works.

Is there anyway around this?

Many thanks!

**Comment by GooberOne** [comment]
Yeah- it doesn't work for me either.
