### ISSUE TITLE
Assimilation deletes the eternal steak from artifacts

### ISSUE THREAD

**Issue by Melechtna** [MoriyaShiine/enchancement#131]
### Mod version

1.19-14

### A description of the issue

I have a server setup with this mod, and the mod artifacts. Artifacts has an item called the eternal steak, which can be eaten an infinite number of times. If assimilation gets ahold of it, it destroys it instead of the expected behavior. I also can't seem to find a way to blacklist the food item.

**Comment by MoriyaShiine** [comment]
You can add items to `enchancement:cannot_assimilate` to disable it. I'll probably add the Artifacts foods to the tag whenever I get to next updating the mod

**Comment by Melechtna** [comment]
> You can add items to `enchancement:cannot_assimilate` to disable it. I'll probably add the Artifacts foods to the tag whenever I get to next updating the mod

Where in the config is this located? That's the part I'm having a hard time finding.

**Comment by MoriyaShiine** [comment]
It's not in the config, it's an item tag you'd add with a datapack

**Comment by Melechtna** [comment]
> It's not in the config, it's an item tag you'd add with a datapack

While I can make the datapack, why not add an additional section to the assimilation json to allow for specifying items for simplicity?

**Comment by MoriyaShiine** [comment]
Datapacks are about as simple as it can get; config files are for universal settings and reserved only for things that can't be done with datapacks, while datapacks are per world and much more modular

**Comment by Melechtna** [comment]
> Datapacks are about as simple as it can get; config files are for universal settings and reserved only for things that can't be done with datapacks, while datapacks are per world and much more modular

kubejs works too, as one of my modpack helpers just pointed out, but thanks!

**Comment by MoriyaShiine** [comment]
I still want to keep this open so I can remember to include it in the default datapack; I might also make it so it still eats the food but doesn't consume the item

**Comment by Melechtna** [comment]
> I still want to keep this open so I can remember to include it in the default datapack; I might also make it so it still eats the food but doesn't consume the item

The person that's helping me tells me this isn't a problem with a newer version of Artifacts. I just tested it myself, so it looks like the other mod author already handled this.
