### ISSUE TITLE
Hitbox glitches when sliding under staircases

### ISSUE THREAD

**Issue by sombrae** [MoriyaShiine/enchancement#132]
### Mod version

1.19-14 (lastest 1.19.2 version)

### A description of the issue

See for yourself.

https://drive.google.com/file/d/1fBFZ8OeLpe5y6brTGSAzrrzrhdgSY6ax/view?usp=sharing

**Comment by MoriyaShiine** [comment]
I _think_ this is a compatibility issue with Pehkui and some other mod, but in recent versions, Slide no longer changes the hitbox and uses the default crawl pose
