### ISSUE TITLE
really big issue, server crash

### ISSUE THREAD

**Issue by KarmaLikesAxolotls** [MoriyaShiine/enchancement#137]
### Mod version

Any 1.19.2 version 

### A description of the issue

I dont understand anything about it but someone on the quilt discord said "the mod is trying to mixin a client class even on a server instance, but not a random client class, the main one, MinecraftClient itself" and its a really big issue

### Log or crash report

https://gist.github.com/KarmaLikesAxolotls/3ffee987038f704127c2d47062843ba0

**Comment by MoriyaShiine** [comment]
I don't know why you're reporting this to me, Enchancement isn't mentioned anywhere in the log and observably works on servers

**Comment by KarmaLikesAxolotls** [comment]
confirmed, they confused it for effective lmao, fixed the issue thanks for the help anyway
