### ISSUE TITLE
short-spamming "phasing" bows can cause high damage

### ISSUE THREAD

**Issue by wizardnoodle23** [MoriyaShiine/enchancement#14]
### Mod version

enchancement-1.18-13

### A description of the issue

(not latest version -- dont know if relevant)
shooting a bow with phasing enchantment as soon as possible can do damage equivalent to a fully charged shot

heres a short video of it, because it cant be demonstrated with images:
https://user-images.githubusercontent.com/106776338/171734664-1c07a6d9-571d-40be-8351-d8a0f88f1622.mp4

if it cant be recreated, im using ~160 mods so its pretty much lost :/

**Comment by MoriyaShiine** [comment]
Yeah I can't reproduce :(

If you ever find what causes it, feel free to open another issue
