### ISSUE TITLE
Treasure Enchants carrying 2 enchants when renamed

### ISSUE THREAD

**Issue by magmabits** [MoriyaShiine/enchancement#143]
### Mod version

1.20-8

### A description of the issue

While renaming a treasure enchanted book, like Swift Sneak, Soul Speed or Mending, the enchanted book gains a new enchant.
![grafik](https://github.com/MoriyaShiine/enchancement/assets/66217030/9bb61695-7af1-4713-99ae-97256cefe3ec)
![grafik](https://github.com/MoriyaShiine/enchancement/assets/66217030/5f2836ab-0fc6-4149-b847-a668132c644b)
![grafik](https://github.com/MoriyaShiine/enchancement/assets/66217030/200c6a1d-172a-4e09-ba72-56ddb9d353a3)

**Comment by magmabits** [comment]
It does not add a new enchant to enchantments like Efficiency, Molten, Accumulate, Double Dash, etc. since they are not treasure enchantments.

**Comment by MoriyaShiine** [comment]
This is only possible when giving illegal enchantments with commands via nbt, or by config editing to allow and then disallow after obtaining. Either way, discussed on the Rattiest Gang discord that it's not worth fixing since it's so circumstantial
