### ISSUE TITLE
Crawling is disabled by Buoy

### ISSUE THREAD

**Issue by AllyJaxx** [MoriyaShiine/enchancement#145]
### Mod version

1.20-8

### A description of the issue

this has been an issue for a long ass time but I have just never bothered to report it.

https://github.com/MoriyaShiine/enchancement/assets/64360185/ba1576c7-6e4f-417e-8875-44e861298bb1

### Log or crash report

https://gist.github.com/AllyJaxx/86d9196d76aab9f59e3ca1d44c4e5cfd

**Comment by MoriyaShiine** [comment]
wtf lmao

**Comment by AllyJaxx** [comment]
genuinely more curious how this one hasn't been reported by anyone than how it's even a thing at this point, I last played this mod _maybe_ 9 months ago so I thought it would probably have been fixed but ig not lol

**Comment by MoriyaShiine** [comment]
Yeah people tend to just, not report bugs

**Comment by MoriyaShiine** [comment]
It happens because swimming and crawling are the same pose lol

**Comment by AllyJaxx** [comment]
OH that makes sense then, sounds like that'll be a real fun one to fix then.

Sidenote, apologies for not reporting this sooner, I am admittedly lazy as hell and just never bothered if I'm being honest

**Comment by MoriyaShiine** [comment]
Don't worry about it, I had a laugh with a friend upon seeing it; they knew about it and never told me because they thought it was intentional lmao

**Comment by AllyJaxx** [comment]
Well good to know I wasn't the only one who found it then lol
