### ISSUE TITLE
Unbreaking Changes Flag is 0 by default

### ISSUE THREAD

**Issue by HaipaDev** [MoriyaShiine/enchancement#146]
### Mod version

1.20-8

### A description of the issue

Yeah I was making a modpack and at some point I realized all tools and weapons are unbreakable
Then I eliminated some culprits, it landed on Enchancement
I guess my fault for not reading the description properly, but still not sure if 0 by default is intended, if not sorry for false report, great mod

**Comment by MoriyaShiine** [comment]
It's intentional
