### ISSUE TITLE
incompatibility with certain mods?

### ISSUE THREAD

**Issue by Whazzzaap** [MoriyaShiine/enchancement#147]
### Mod version

1.20.1 fabric

### A description of the issue

so im trying to add enchancement with my modpack but it cant work as for some reason the mods enderman overhaul and pick your poison make it so the game doesn't boot up. is there any way to fix this?

### Log or crash report

crash report

**Comment by MoriyaShiine** [comment]
Not without a log

**Comment by Whazzzaap** [comment]
> Not without a log

how do i send one?

**Comment by MoriyaShiine** [comment]
In the root of your instance there's a crash-reports folder (assuming it crashed), otherwise in logs send latest.log

**Comment by Whazzzaap** [comment]
> In the root of your instance there's a crash-reports folder (assuming it crashed), otherwise in logs send latest.log

alright found it, sending now

**Comment by Whazzzaap** [comment]
[crash-2024-01-18_18.11.13-clientenchancement.txt](https://github.com/MoriyaShiine/enchancement/files/13984143/crash-2024-01-18_18.11.13-clientenchancement.txt)

**Comment by MoriyaShiine** [comment]
Seems to work for me. Try removing mods until it stops crashing and let me know which one was causing it

**Comment by Whazzzaap** [comment]
the only ones were enderman overhaul and pick your poison

**Comment by Whazzzaap** [comment]
once i removed those two then the game was running fine

**Comment by MoriyaShiine** [comment]
I can run with Enchancement, Pick Your Poison, and Enderman Overhaul. I'm not really sure what the issue is

**Comment by MoriyaShiine** [comment]
Found it. It's Geckolib Iris Compat

**Comment by MoriyaShiine** [comment]
They use an @ Overwrite which is incompatible with all other mixins, so I cannot do anything about this. I suggest reporting it to them

**Comment by Whazzzaap** [comment]
ah thank you

**Comment by Whazzzaap** [comment]
youre my life saver holy
