### ISSUE TITLE
Compatibility issue with Mystical Agriculture

### ISSUE THREAD

**Issue by MirroZero** [MoriyaShiine/enchancement#148]
### Mod version

1.20-9

### A description of the issue

There seems to be an issue between the 2 mods, since if both are being used the game will crash at start up, leaving an Error Code: 1.
I'm unsure which mod's fault it is, so to play it safe I figured it would be better to let both creators know.

### Log or crash report

https://gist.github.com/MirroZero/d625e52999cd7fdeda35c8a2e3b8aeac

**Comment by MoriyaShiine** [comment]
Cucumber is using an old version of Porting Lib; newer versions work fine, so I'd report to them and in the meantime you can "fix" it by installing Porting Lib as a normal mod and Fabric Loader will load the new version
