### ISSUE TITLE
Enchancement and Essential mod

### ISSUE THREAD

**Issue by Lotikus** [MoriyaShiine/enchancement#153]
### Mod version

1.20.1

### A description of the issue

Me and a Friend wanted to play the Enchancement mod together through essential mod and it said that i or he needed to install Enchancement in the Process we tried multiple modpacks to see if the Enchancement mod is the problem or essential mod but the problem only accured by enchancement we then  checked if we both had the same version (we did) and the problem was still there.
is there a way to solve the problem or a way to avoid it and to play together (without paying for a server)

**Comment by MoriyaShiine** [comment]
I've played with Enchancement on Essential just fine many times, but without a log I have no idea what would be the issue
