### ISSUE TITLE
Molten-related server crash.

### ISSUE THREAD

**Issue by RabbyDevs** [MoriyaShiine/enchancement#155]
### Mod version (NOT Minecraft version)

1.20-12

### A description of the issue

No specific steps but it is likely due to using Molten in the nether.

### Log or crash report

https://gist.github.com/RabbyDevs/a5fc6524fb2c8498e6dee71ebb57def9

**Comment by MoriyaShiine** [comment]
Seems to only happen with either Observable or Carpet. Can you see which one is causing it?
