### ISSUE TITLE
Enchancement mod ain't working on server 

### ISSUE THREAD

**Issue by Univernal** [MoriyaShiine/enchancement#156]
### Mod version (NOT Minecraft version)

1.20.1

### A description of the issue

So basically, i have the mod on both the server, and my client, but whenever i add the mod onto the server, it just says Registery Remapping failed: Null. and i haven't found anyone else who has gotten this issue.
<img width="958" alt="Screenshot 2024-02-05 160252" src="https://github.com/MoriyaShiine/enchancement/assets/159036080/54580c53-ed00-45b0-beb0-d59d78c53c04">

### Log or crash report

Registery Remapping failed: null

**Comment by Univernal** [comment]
this is my first time reporting an issue like this, soo if there anymore info you need, ill gladly try to give em.

**Comment by MoriyaShiine** [comment]
Mod version is invalid and no log file is attached.

Please find the log file from your logs folder (server and client) and upload it via gist as linked on the issue template; a disconnect screen is not a log

**Comment by MoriyaShiine** [comment]
You don't need to apologize, mistakes happen :p
I just can't do anything without a log
