### ISSUE TITLE
Items with infinite durability

### ISSUE THREAD

**Issue by Milcki** [MoriyaShiine/enchancement#159]
### Mod version (NOT Minecraft version)

1.19-14

### A description of the issue

Items have infinite durability (like the unbreakable tag)

Sorry for bad english, im a braziliam 

### Log or crash report

.

**Comment by Ohnogotscammed** [comment]
I am pretty sure that is a feature. I looked into it and on its Modrinth page it says "Remove durability from most aspects of the game. There is an item tag to allow certain items to keep durability"

**Comment by MoriyaShiine** [comment]
^ That's part of the mod
