### ISSUE TITLE
SUGGESTION: Config option for "Golden Apples can only be eaten when Hungry"

### ISSUE THREAD

**Issue by Xitricj** [MoriyaShiine/enchancement#161]
### Mod version (NOT Minecraft version)

1.20-17

### A description of the issue

The title is pretty self-explanatory. Adding this brings more customizability to Enchancement, and some people (including me) don't like the new Golden Apple rework in 1.20-10. 

### Log or crash report

I have to put something here otherwise I can't submit it :P

**Comment by MoriyaShiine** [comment]
Please read the issue template, issues are not for suggestions. Regardless, this is already a config option
