### ISSUE TITLE
Compat related crash with the latest 1.19.2 build

### ISSUE THREAD

**Issue by Sunconure11** [MoriyaShiine/enchancement#164]
### Mod version (NOT Minecraft version)

enchancement-1.19-19

### A description of the issue

It would seem build 19 crashes on 1.19.2, but going back to an older build works fine. This appears to be a compat issue. I suggest checking more recent builds for this issue, as well.

### Log or crash report

https://gist.github.com/Sunconure11/f53028310814e010ac07849e5025892c

**Comment by MoriyaShiine** [comment]
Works in 1.20.1
