### ISSUE TITLE
Enchanting Limit is 0 But i cant use fortune with efficiency after unblocking fortune from the Blacklist

### ISSUE THREAD

**Issue by AngelAether** [MoriyaShiine/enchancement#167]
### Mod version (NOT Minecraft version)

enchancement-1.20-17

### A description of the issue

I for some reason cant combine fortune and efficiency, Not only that but it allowed a book of efficiency to be put on the Fortune pickaxe but then turned it into an unbreaking enchantment rather than efficiency, which is useless because my tools Do Not Break.

I do have the EasyAnvils mod (version: v8.0.0-1.20.1-Fabric) 

![image](https://github.com/MoriyaShiine/enchancement/assets/99603436/cfc6e332-7052-4ad6-bb1f-fd70534addd5)

![image](https://github.com/MoriyaShiine/enchancement/assets/99603436/4963f55b-e9f6-4d2b-9d6e-15dcd3291275)

![image](https://github.com/MoriyaShiine/enchancement/assets/99603436/cfc3ef7f-934b-482a-abfb-2da65aa898f8)

### Log or crash report

I dont know what to put here.

**Comment by AngelAether** [comment]
Im going to remove the easyanvils mod and i'll update this post.

**Comment by AngelAether** [comment]
EasyAnvils was not the problem.

**Comment by AngelAether** [comment]
The reason why i havent provided a log is because i dont know How to and i dont know if combining tools not being a thing is a bug or if its just a feature?

**Comment by AngelAether** [comment]
Cus honestly if i cant find a way to disable this i'll probably just remove the mod sadly because i have enjoyed the mod for a week or two now and found no issues until this halted any progress i was making

**Comment by MoriyaShiine** [comment]
Are you able to combine any other enchantments? Do you have Unbreaking enabled? I'm not sure why this is happening, nor can I replicate the issue
