### ISSUE TITLE
Doesn't really work with other enchantment mods

### ISSUE THREAD

**Issue by tikicat1** [MoriyaShiine/enchancement#171]
### Mod version (NOT Minecraft version)

Enchancement 1.20-21

### A description of the issue

I am using the armor abilities enchantment mod and I can't put them on my armor in the enchanting table because only 4 enchantments are appearing
![image_2024-04-07_185203459](https://github.com/MoriyaShiine/enchancement/assets/83901915/06e1a943-20aa-47b5-9fbe-07420b2d62dc)

### Log or crash report

It doesn't crash

**Comment by MoriyaShiine** [comment]
Armor Abilities doesn't look like it adds any weapon enchantments, so that screenshot looks fine to me. Could you send a screenshot of an armor piece in the Enchanting Table?

**Comment by tikicat1** [comment]
no thats my bad i am just an idiot thx tho
