### ISSUE TITLE
some problems I found

### ISSUE THREAD

**Issue by peow** [MoriyaShiine/enchancement#174]
### Mod version (NOT Minecraft version)

Fabric v1.20-23

### A description of the issue

* **1)** the texture of some mobs looks strange when they are frozen
![2024-04-18_10 12 55](https://github.com/MoriyaShiine/enchancement/assets/105888751/758a599f-6252-4f37-960f-cecf793810bb)
![2024-04-18_10 15 40](https://github.com/MoriyaShiine/enchancement/assets/105888751/fb56c02c-f276-4087-a01b-4016e60a21cf)

* **2)** boots with the Buoy enchantment cannot descend when sneaking in water bubbles (from Soul Sand)

and if you are thrown up very quickly, when you fall into the water bubbles you will be taken down
![2024-04-18_10 28 53](https://github.com/MoriyaShiine/enchancement/assets/105888751/2777576b-662f-41be-8387-5e227e1c3df3)
![2024-04-18_10 28 54](https://github.com/MoriyaShiine/enchancement/assets/105888751/44a5a036-121e-47fe-8d67-ab1f91314f13)
![2024-04-18_10 28 54_2](https://github.com/MoriyaShiine/enchancement/assets/105888751/34e34528-a40b-4d6d-ae43-046af490ecdb)
![2024-04-18_10 28 54_3](https://github.com/MoriyaShiine/enchancement/assets/105888751/9d144bda-919f-48cc-98e3-d4c8078a20bf)

* **3)** the mod is turning enchanted equipment into **Epic** Rarity instead of **Rare** and there is no option to disable this
In Minecraft, enchanted items are considered "Rare" (https://minecraft.fandom.com/wiki/Rarity#Tiers) and I'm using a texture that makes the Tooltip of Rare items blue, and Epic items gold, but when using this mod the enchanted equipment becomes golden because of the rarity that has changed
![2024-04-13_16 19 17](https://github.com/MoriyaShiine/enchancement/assets/105888751/6ca67c62-8f19-45df-b59b-b90244ef3926)
![2024-04-13_16 20 58](https://github.com/MoriyaShiine/enchancement/assets/105888751/f031aefd-c612-42c7-a00d-4e2378342593)

Note that not only the tooltip has changed but also the color around the item, which the "Item Borders" mod adds, which follows the rarity of Minecraft Vanilla
without Enchancement the border is blue (Rare), with Enchancement the border is purple (Epic)

* **4)** this one is just a visual bug, when you bury a Shulker with the Bury enchantment, it no longer opens the shell when shooting 

![2024-04-18_10 26 45](https://github.com/MoriyaShiine/enchancement/assets/105888751/74186417-565c-43cb-aeea-eda550730a53)

----------

If it is possible to fix these bugs, please publish a update to **1.20.1**

### Log or crash report

https://gist.github.com/peow/313aa1c7d3ff5e11936f2cec83f69ae3 in this log im not using the mod that shows the item rarity

**Comment by MoriyaShiine** [comment]
- 1: I'm unable to fix this, all Frostbite does is apply the ice texture to the model, but the model doesn't know which parts of which planes are transparent or not.
- 2: The random descending happens with all non-water blocks and I'm not sure why, I still need to figure that out.
- 3: This is intentional. Single Level Mode changes item rarity to indicate whether or not the enchanted item is strongly enchanted (epic) or weakly enchanted (rare).
- 4: Interesting, I'll look into it.

Please open separate issues for 2 and 4

**Comment by MoriyaShiine** [comment]
Yes, open an issue
