### ISSUE TITLE
Unable to find the compatibility issue

### ISSUE THREAD

**Issue by Sagirem1** [MoriyaShiine/enchancement#178]
### Mod version (NOT Minecraft version)

1.20-24

### A description of the issue

I love the mod so I tried installing it on a tweaked version of the "Better MC" modpack to see the configs and if there were enchantments from other mods that would cause issue. However, I wasn't even able to start the game and I have no idea why...

### Log or crash report

https://gist.github.com/Sagirem1/637026ef7b06265889b475f27772ae44

**Comment by MoriyaShiine** [comment]
Geckolib causing crashes once again :/
I think at this point I'm just gonna drop support for it, this is the fourth time I've had to change it now. Thanks for the report!

**Comment by Sagirem1** [comment]
Oh so does it mean there's no way to fix it... ? :'(

**Comment by MoriyaShiine** [comment]
New update removes geckolib compat, should fix the crash
