### ISSUE TITLE
1.20.5/6 support

### ISSUE THREAD

**Issue by cph101** [MoriyaShiine/enchancement#179]
### A description of the issue

Well since I can’t access the discord (yes I did appeal but no decision yet afaik), I might as well make an issue here.

I’ve had a look at some of the code and attempted a partial port, I thought I’d mention the differences I came across:
- It seems as if NBT has multiple crucial methods missing, yet they still exist for entities. `RegistryLookup` is also now in use
- Client-side, I think you can no longer get the player model (or at least not in the same place), so it isn’t possible to send whether it’s slim or not to the server when for frostbite
- Packets are constructed using a class extending `CustomPayload`, they are registered with a `Id<CustomPayload>(Identifier)` instead of a normal identifier, and they are now serialized with codecs instead of `ByteBuf`s
- Step height now exists in vanilla

Would be nice to have some eta on this since it’s required for Impaled, but I understand this is a very large undertaking.

**Comment by MoriyaShiine** [comment]
Many dependencies are not yet updated, and I'm giving time for them to mature before updating any of my mods. Besides, future versions of my mods will be on ko-fi first anyways.

Please don't open issues asking for me (or any mod author) to update mods to a version that barely just released, it only makes us feel rushed.

Eta between now and the heat death of the universe.

**Comment by cph101** [comment]
Fair enough, no problem :)
