### ISSUE TITLE
Add presistent tag to the wood logs

### ISSUE THREAD

**Issue by Disketaa** [MoriyaShiine/enchancement#18]
### Mod version

1.18-17

### A description of the issue

If it possible, can you add **presistent** tag, (similar on leaves), to the logs. And make Timber enchant affect only trunks with that tag. So it could destroy only world-generation trees, not player-placed.

**Comment by MoriyaShiine** [comment]
Minecraft doesn't know the difference between player placed and natural logs. Please use the discord for suggestions, these are flooding the bug tracker lol

**Comment by MoriyaShiine** [comment]
Not without a massive increase in world file size, which isn't worth it. I've instead already added a 7 block radius for Lumberjack, so it for the most part will only gather trees
