### ISSUE TITLE
Conflict with "Tool Leveling+" Fabric Mod

### ISSUE THREAD

**Issue by AbsoluteF4** [MoriyaShiine/enchancement#182]
### Mod version (NOT Minecraft version)

1.20-25

### A description of the issue

Conflict with "Tool Leveling+" Fabric mod where durability are not visually registered and tools above enchanting limit (ex. Sharpness 100) acts like a normal sharpness 5

### Log or crash report

no issues were present in the logs nor i have access to old logs containing the mod loading in the server

**Comment by MoriyaShiine** [comment]
Enchancement disables durability and enchantment levels by default. You can change this in the config
