### ISSUE TITLE
Brimstone projectile is invisible when using Iris shaders

### ISSUE THREAD

**Issue by TheTrueYak** [MoriyaShiine/enchancement#184]
### Mod version (NOT Minecraft version)

1.20-26

### A description of the issue

The Brimstone projectile beam is completely invisible when using shaders, (on both Iris 1.6.17 and Iris 1.7.0, the only versions compatible with Sodium 0.5.8) leaving only the impact particles to indicate where the beam went. The beam can only become visible again by disabling shaders. 

![2024-05-25_01 13 04](https://github.com/MoriyaShiine/enchancement/assets/107325508/5f88b5bf-7d46-4e94-8853-7afbc382da63)
![2024-05-25_01 14 28](https://github.com/MoriyaShiine/enchancement/assets/107325508/133b4a64-dcc0-4f5d-9cba-0df5aad6a67d)

### Log or crash report

https://gist.github.com/TheTrueYak/fc8a38ae3f6d8bbea14ad32ab574e1c7

**Comment by MoriyaShiine** [comment]
Given all I do is draw a plane (multiple times), I have absolutely no idea why this would happen. From what I hear though, Iris has to rewrite a whole bunch of stuff for 1.21 so I would wait to see if it's still an issue when that eventually comes out.
