### ISSUE TITLE
Enchant suggestions

### ISSUE THREAD

**Issue by Disketaa** [MoriyaShiine/enchancement#19]
### Mod version

1.18-17

### A description of the issue

Ideas for enchants:

Enchantment on axe, that can turn stripped logs into normal ones
Enchantment on hoe, that can replant destroyed crops
Enchantment on hoe, that can expand the radius can destroying crops

**Comment by MoriyaShiine** [comment]
Suggestions on discord

**Comment by Disketaa** [comment]
Sorry, but I wrote in discord, but doesn't get an answer
