### ISSUE TITLE
balm incompatibilityy cant sneak or sprint

### ISSUE THREAD

**Issue by ImBehinYa** [MoriyaShiine/enchancement#192]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.20-26

### A description of the issue

cant sprint or shift when using https://modrinth.com/mod/balm and https://modrinth.com/mod/enchancement

### Log or crash report

.

**Comment by MoriyaShiine** [comment]
1.20-26 is not the latest possible mod version or for the latest possible Minecraft version. Please verify that both of these checkboxes are accurate and that the issue still occurs, and I'll reopen the issue.

**Comment by ImBehinYa** [comment]
> 1.20-26 is not the latest possible mod version or for the latest possible Minecraft version. Please verify that both of these checkboxes are accurate and that the issue still occurs, and I'll reopen the issue.

So only latest version is supported, so 1.20.1 won't be supported anymore?

**Comment by MoriyaShiine** [comment]
Yes, that's what those checkmarks that you read and checked were supposed to tell you

**Comment by ImBehinYa** [comment]
Sorry for the inconvenience

**Comment by MoriyaShiine** [comment]
All good. If you can verify it still happens in 1.20.6 then I'll reopen the issue
