### ISSUE TITLE
Sniper Bow from Amethyst Imbuement cannot use enchantment Brimstone.

### ISSUE THREAD

**Issue by Smug-Bab** [MoriyaShiine/enchancement#193]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.20-26

### A description of the issue

When using the Sniper Bow with the Brimstone enchantment, no hearts are taken and the projectile does zero damage.
![2024-06-24_22 32 30](https://github.com/MoriyaShiine/enchancement/assets/87583840/f66cfdb6-0dc5-4212-b5ef-640135bf1a02)

### Log or crash report

no crashe

**Comment by MoriyaShiine** [comment]
1.20-26 is not the latest possible mod version or for the latest possible Minecraft version. Please verify that both of these checkboxes are accurate before submitting an issue.

Brimstone's code has been changed entirely in 1.20.6, so I'm not sure this will still occur in recent versions. Whenever Amethyst Imbuement also updates, let me know if it's still an issue and I'll reopen the issue if that's the case
