### ISSUE TITLE
[1.20] InvertedList and allowedEnchantments Is utterly broken

### ISSUE THREAD

**Issue by TheStarlessBandit** [MoriyaShiine/enchancement#194]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.20-6

### A description of the issue

So in the enchancement.json config when you set "invertedList" to true, it would make it so "allowedEnchantments" would be the blacklist and any enchant on there would be disabled ingame, as it should be. However, setting it to true will completely ignore whatever is in the "allowedEnchantments" section and will disable every single enchant the mod offers and replace them with the vanilla ones, essentially removing the mod.
Setting invertedList to false and putting let's say, the vanilla enchants you want to keep, it will again ignore whatever is on the allowedEnchantments section and will remove ALL vanilla enchants, even if you specified that you want to keep some, but making all the mod enchantments available.
Essentially 2 extremes.
I have no idea if it's something I don't understand or there somehow is a typo in the script, even though it's the same script I used on 1,18.2 and it worked fine. I'll send the json file.

### Log or crash report

https://gist.github.com/TheStarlessBandit/85b7ffe7fdb01bf00c03d6f9a5cbf52a

**Comment by ILLUMN8N** [comment]
wait how was this solved?
