### ISSUE TITLE
gale issue

### ISSUE THREAD

**Issue by hextheslime** [MoriyaShiine/enchancement#195]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

v1.19-19

### A description of the issue

Boots from other mods (specifically Armor of the Ages and a custom private mod) only support one double jump from gale.

### Log or crash report

none

**Comment by MoriyaShiine** [comment]
Please verify that you have actually read the check boxes you marked.

This is not an issue, enchantment strength is based on the enchantability of items, if it is low then the item is weakly enchanted. You can override this by adding the items to the `enchancement:weakly_enchanted` or `enchancement:strongly_enchanted` item tags.
