### ISSUE TITLE
Enchancement tooltipfix dependency on quilt 1.19.2

### ISSUE THREAD

**Issue by Ro6in1** [MoriyaShiine/enchancement#196]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1-19.19

### A description of the issue

The quilt version of the mod has a dependency on ToolTipFix which doesn't have a quilt version. When I try and install the fabric version anyway, it doesn't launch. Could just be me being stupid here but I'm honestly lost on what to do. 

![image](https://github.com/user-attachments/assets/30353d5c-0fcd-456f-b83b-99e199aabb90)

### Log or crash report

crash-2024-08-25_22.57.23.3490-quilt_loader.txt

edit: idk how to properly link a crash report im new here

**Comment by MoriyaShiine** [comment]
1.19 is unsupported, please read the check boxes you are marking.

TooltipFix should work fine on quilt, if it doesn't then I suggest asking in a support discord.
