### ISSUE TITLE
Compatibility with Spectrum

### ISSUE THREAD

**Issue by tivvo** [MoriyaShiine/enchancement#198]
### Confirmations

- [ ] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

enchancement-1.20-26.jar

### A description of the issue

Latest possible minecraft version seems 
Compatibility with "Spectrum" causes a crash.
That's kinda it, not sure if this happens in the latest verisons but I will test and report back.

### Log or crash report

https://gist.github.com/tivvo/a454831c28c7d623896b49f0a34bcdf9

**Comment by MoriyaShiine** [comment]
Reverting to Spectrum 1.7.16 seems to fix it, Enchancement for 1.20 is unsupported so I suggest doing that for the time being until Spectrum updates to a new Minecraft version
