### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by DemonfallPG3D** [MoriyaShiine/enchancement#20]
### Mod version

1.18-27

### A description of the issue

So not sure if this is a glitch i'd just like some help i want to download the mod but it requires mods from both fabric and forge (bookshelf for example) and seeing as this is my first time ever installing mods, I just wanted to know how to do so. Thanks!

**Comment by MoriyaShiine** [comment]
You need to install the fabric versions of those mods (as well as the fabric loader). Please join the discord if you need further help, github is for bug reports
