### ISSUE TITLE
Crashing with Sparkweave Engine

### ISSUE THREAD

**Issue by DiamondJMS** [MoriyaShiine/enchancement#200]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.21-r5

### A description of the issue

When only these mods are active (and Fabric API ofc), the game crashes and says "Process exited with code 2."
With other mods like Sodium and Friends and Foes, the game opens the Fabric error screen and a giant message is shown.
Sparkweave Engine's version is 0.503.0+Fabric
I am using Prism Launcher

### Log or crash report

https://gist.github.com/DiamondJMS/50b15775c810a7aa66575a51eadaf247

**Comment by MoriyaShiine** [comment]
Sparkweave Engine 0.503.1 seems to fix this
