### ISSUE TITLE
Crash when opening Creative Inventory with Cyanide

### ISSUE THREAD

**Issue by Tenuuu** [MoriyaShiine/enchancement#201]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.21-r7

### A description of the issue

When trying to open up the inventory whilst in creative mode, the game will freeze up and crash. Opening in survival does not cause the game to crash

### Log or crash report

https://gist.github.com/Tenuuu/f2cb0949a8c73ab2bcf21acc83fab244

**Comment by MoriyaShiine** [comment]
That's a lot of mods, can you find out which ones are causing the crash when combined with Enhancement?

**Comment by Tenuuu** [comment]
Did some searching through and found the mod that causes this incompatibility is "Cyanide"

**Comment by MoriyaShiine** [comment]
Cyanide seems to completely ignore Enchancement's enchantment disabling feature, odd.
