### ISSUE TITLE
Lumberjack enchantment does not use up durability

### ISSUE THREAD

**Issue by BlueStaggo** [MoriyaShiine/enchancement#203]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

v1.21-r12

### A description of the issue

When chopping down trees with an axe enchanted with the Lumberjack enchantment, its durability does not get used up. I assume this is an oversight due to the mod disabling durability by default, but for players who want to play the mod with durability enabled, it would be a good balancing change to make the enchantment use up durability on use.

### Log or crash report

Not needed

**Comment by MoriyaShiine** [comment]
This was indeed an oversight, thanks!
