### ISSUE TITLE
Config file not working - reverting to default 1.19.2

### ISSUE THREAD

**Issue by resi96** [MoriyaShiine/enchancement#210]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.19-19

### A description of the issue

When loading my mods, the config for the enchantments mod reverts to default from my edited config.
[latest.log](https://github.com/user-attachments/files/17940713/latest.log)

### Log or crash report

https://gist.github.com/resi96/5e86169c6b55123ba55aa69e9ba799bf.js

**Comment by MoriyaShiine** [comment]
1.19 is unsupported, please verify you have read the check boxes you marked.

Either change the config only through mod menu, or edit the json file manually only while the game is closed. This is not a bug with Enchancement, editing text files while they are in use / being written to will always be overwritten by any program.
