### ISSUE TITLE
Items that have durability no longer have durability

### ISSUE THREAD

**Issue by Enderborn1235** [MoriyaShiine/enchancement#212]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.21-r14

### A description of the issue

Whenver I use a tool. it no longer has durability, and  can be used indefinitely

### Log or crash report

https://gist.github.com/Enderborn1235/a5cb84cf86ab01546df205e51cc739ad

**Comment by MoriyaShiine** [comment]
This is a normal feature of the mod
