### ISSUE TITLE
Enchantment materials dupe on 1.19.2

### ISSUE THREAD

**Issue by slyfily2** [MoriyaShiine/enchancement#214]
### Confirmations

- [ ] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.19-19

### A description of the issue
(1.19.2)

Removing the item you are enchanting from the GUI drops the materials as well as keeping them in the GUI (i.e. 2 diamonds in the GUI, when taking the tool/armor piece out of the GUI 2 diamonds will be dropped on the floor and 2 diamonds stay in the GUI)

https://streamable.com/v27esg (Testing it again, its a little weird but the point still stands)

### Log or crash report

https://gist.github.com/slyfily2/5401e2ec836e4b19de0996405eab4d6d

**Comment by MoriyaShiine** [comment]
Unable to replicate in 1.21.4
