### ISSUE TITLE
Persistent unexpected error

### ISSUE THREAD

**Issue by EnierAragon** [MoriyaShiine/enchancement#216]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.21-r14

### A description of the issue

This crash has been occurring from time to time in my mod pack, it seems to be coming from here, I am attaching the report in case it is useful.
[https://mclo.gs/uEwR03U](https://mclo.gs/uEwR03U)

### Log or crash report

https://gist.github.com/EnierAragon/5c4f7d515984e92f63d9ccd019d3d29b

**Comment by MoriyaShiine** [comment]
It seems to be caused by Apoli/Origins, does it happen without it?

**Comment by MoriyaShiine** [comment]
This currently does not apply however, as the latest version of Enchancement does not run on a version where Origins exists on (as per the checkboxes, which are inaccurately marked). As such the issue will be closed, but feel free to seek help in the discord in case anyone knows of a solution
