### ISSUE TITLE
Tools  Durability is not drain

### ISSUE THREAD

**Issue by PengWanYT** [MoriyaShiine/enchancement#217]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.21.4-r1

### A description of the issue

There issues about tools, when I am installed enhancement mod, I am notice all tool durability is inf, can't drain anymore, can you fix it?

### Log or crash report

No :(

**Comment by MoriyaShiine** [comment]
This is an intentional feature of the mod. You can disable it in the config

**Comment by PengWanYT** [comment]
Ohhhh so it config? Thx sir :0
