### ISSUE TITLE
Game crash during crossbow reload

### ISSUE THREAD

**Issue by ninjaguardian** [MoriyaShiine/enchancement#218]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version. (do you mean 1.21.4? because if so, then no.)
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.20-26

### A description of the issue

I just loaded my crossbow and the game crashed. This issue could possibly be related to [firework frenzy](https://github.com/CammiePone/FireworkFix).

### Log or crash report

https://gist.github.com/ninjaguardian/711b83999233ea1e0cec3edb3f106087

**Comment by MoriyaShiine** [comment]
It's a rare crash that happens sometimes, it's not common. Fixed already in 1.21
