### ISSUE TITLE
Issues with Frozez mob effect and Chirp's Wildlife

### ISSUE THREAD

**Issue by Thingw31** [MoriyaShiine/enchancement#27]
### Mod version

1.18.1

### A description of the issue

As written, any mob in Chirpy's wildlife when frozen crashes the server, If a fix ever comes out for it id love if the fix was backported to 1.18.1 but as long as its fixed ill be happy.

### Log or crash report

https://gist.github.com/Thingw31/c1fddf406868564b139853cb472a7f97

**Comment by MoriyaShiine** [comment]
Bruh how are both mods that cause this issue closed source

The source for Chirpy's Wildlife is not visible, meaning I am unable to fix this and I suggest reporting to them. See #11 for a similar situation
