### ISSUE TITLE
Incompatibility with The Graveyard

### ISSUE THREAD

**Issue by floral-qua-floral** [MoriyaShiine/enchancement#29]
### Mod version

1.19-1

### A description of the issue

Game fails to launch with finallion's [The Graveyard](https://modrinth.com/mod/the-graveyard-fabric) mod. No additional window opens, and instead a popup appears within the launcher reading:  
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'graveyard'!
Exit Code: -1
```

* Minecraft 1.19
* Quilt Loader 0.17.1-beta.4-1.19
* Quilt Fabric API 2.0.0-alpha.4 and Quilt Standard Libraries 2.0.0-beta.5
* Enchancement 1.19-1
* Enchantment Descriptions 11.0.4
* Bookshelf 14.0.3
* ToolTipFix 1.0.5
* The Graveyard 1.10
* Geckolib Quilt 3.1.3

### Log or crash report

Log file: https://gist.github.com/floral-qua-floral/ac42d7e201b792183435ee2693dda87d
Crash report: https://gist.github.com/floral-qua-floral/7d2d37a68d670f182b5c9dc6ef208acd

**Comment by MoriyaShiine** [comment]
I'll need to look into how to fix this, but for now try using the Fabric version of Geckolib

**Comment by MoriyaShiine** [comment]
Geckolib Quilt 3.1.6 seems to work fine now
