### ISSUE TITLE
Incompatibility with Truly Treasures

### ISSUE THREAD

**Issue by floral-qua-floral** [MoriyaShiine/enchancement#30]
### Mod version

1.19-1

### A description of the issue

Game fails to launch with In3ffa's [Truly Treasures](https://www.curseforge.com/minecraft/mc-mods/truly-treasures) mod. No additional window opens, and instead a popup appears within the launcher reading:
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'trulytreasures'!
Exit Code: -1
```

* Minecraft 1.19
* Quilt Loader 0.17.1-beta.4-1.19
* Quilt Fabric API 2.0.0-alpha.4 and Quilt Standard Libraries 2.0.0-beta.5
* Enchancement 1.19-1
* Enchantment Descriptions 11.0.4
* Bookshelf 14.0.3
* ToolTipFix 1.0.5
* Truly Treasures 2.0.2

### Log or crash report

Log file: https://gist.github.com/floral-qua-floral/74b912dfe2d4a4ebb323ea642d91f681
Crash report: https://gist.github.com/floral-qua-floral/6eb59aecd21cfa92fbccd9bea0778a39

**Comment by MoriyaShiine** [comment]
Unrelated to Enchancement, Truly Treasures crashes on its own. However you can fix it by installing Cloth Config API, they should mark that as a required dependency.
