### ISSUE TITLE
Other enchants

### ISSUE THREAD

**Issue by IntrepidBlade** [MoriyaShiine/enchancement#31]
### Mod version

1.19.1

### A description of the issue

Can’t add the other enchants into the game via config

**Comment by MoriyaShiine** [comment]
Can't reproduce, works fine on my end adding Sharpness
![2022-06-26_18 25 36](https://user-images.githubusercontent.com/45156123/175837873-f7df3c85-5008-4afb-abbc-3f7b7b1ff2ef.png)

**Comment by IntrepidBlade** [comment]
I did use the quotes Aswell, and ty for ur time
