### ISSUE TITLE
Normal enchants on server not working

### ISSUE THREAD

**Issue by IntrepidBlade** [MoriyaShiine/enchancement#32]
### Mod version

1.19

### A description of the issue

I can't use other enchants on my server with the mod installed, I enabled it in config.
![Screenshot 2022-06-27 134415](https://user-images.githubusercontent.com/106448838/176013256-7c14d0c9-dc0a-4cf4-8d7c-5ea5ddc3f105.png)
![Screenshot 2022-06-27 134448](https://user-images.githubusercontent.com/106448838/176013264-d1982526-df5b-460b-96f5-48b69838cf8a.png)

**Comment by MoriyaShiine** [comment]
The client and server need the same config file. Make sure to update it on both

**Comment by IntrepidBlade** [comment]
ok thanks also how do I update the config file on my side?
