### ISSUE TITLE
1.19 wont work

### ISSUE THREAD

**Issue by UsuaIIyUnusuaI** [MoriyaShiine/enchancement#33]
### Mod version

1.19

### A description of the issue

The relations of the mod requires enchantment descriptions even though the enchantment descriptions mod is still in 1.16.5

**Comment by MoriyaShiine** [comment]
It's been on 1.19 for a while https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3829144

**Comment by UsuaIIyUnusuaI** [comment]
yeah nvm, I just now looked deeper into the version history and found some files 1.19, on the home page for the Enchantment description mods it only says "game version 1.16.5"
