### ISSUE TITLE
Incorrect enchantment given when used in All of Fabric 5

### ISSUE THREAD

**Issue by Grantis622** [MoriyaShiine/enchancement#35]
### Mod version

1.18.2

### A description of the issue

I click the enchantment, it chooses a different one

### Log or crash report

The game crashed whilst mouseclicked event handler Error: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 0 Exit Code: -1

**Comment by MoriyaShiine** [comment]
This doesn't tell me anything; I need a full log or crash report
