### ISSUE TITLE
Config file changes reset after restarting Minecraft

### ISSUE THREAD

**Issue by vukkax** [MoriyaShiine/enchancement#38]
### Mod version

1.19-2

### A description of the issue

Like the title says, after I've made changes to the config json file, I restart the game and the json file resets to its original state. World configurations don't change, but whenever I try adding new enchantments to the main config file it just resets to its original state.

**Comment by MoriyaShiine** [comment]
Does it reset when using Mod Menu, or by manually editing the file? If you're manually editing then it should be done when the game is closed; if it happens with Mod Menu then I'll need to look into it

**Comment by vukkax** [comment]
It was while manually editing, but it seems to work now. Probably I did something wrong, thanks for answering :)

**Comment by MoriyaShiine** [comment]
I see, no worries!
