### ISSUE TITLE
Incompatibility with Backslot mod

### ISSUE THREAD

**Issue by FumpleWumper** [MoriyaShiine/enchancement#39]
### Mod version

1.19-3

### A description of the issue

Enchantments from weapons in a player's backslot will also work on off-hand weapons
For example, if a player has a sword with Frostbite on their backslot, and they throw a unenchanted Trident from their off-hand, the Trident will also deal Freezing damage

**Comment by MoriyaShiine** [comment]
Does this happen with vanilla enchantments too? Can you test if Fire Aspect in a back slot does the same thing

**Comment by FumpleWumper** [comment]
I did some proper testing in creative, and it didn't seem to work with any other enchantments, Vanilla or Enchancement
Even went as far as testing with other Trident enchantments, but in the end it seemed only Frostbite had this interaction

**Comment by MoriyaShiine** [comment]
This seems to be on their end and will happen with any enchantment that overrides onTargetDamaged; vanilla just happens to never use this method. It could be fixed by removing back slot items from EnchantmentHelper#onTargetDamaged
