### ISSUE TITLE
Connection error in multiplayer

### ISSUE THREAD

**Issue by Disketaa** [MoriyaShiine/enchancement#4]
### Mod version

 enchancement-1.18-2.jar

### A description of the issue

![image](https://user-images.githubusercontent.com/76956762/166517954-13c85d54-37ce-400a-9e0a-dda6f684eab5.png)

### Log or crash report

https://gist.github.com/Disketaa/c3c4d11f8d815e5231efa9f380e2c7b3

**Comment by MoriyaShiine** [comment]
Does the connecting client have the same config settings as the server?

**Comment by MoriyaShiine** [comment]
![2022-05-03_13 55 50](https://user-images.githubusercontent.com/45156123/166523278-1f3139bf-3a0f-42b1-be75-554e0d8667ca.png)

Are you sure? I'm able to join just fine

**Comment by Disketaa** [comment]
hmm, i'll double check that
thanks for the quick responce!

**Comment by CammiePone** [comment]
To me this looks like you may have forgotten to restart your server after putting the mod in the mods folder.

**Comment by Disketaa** [comment]
I able to join too, just checked it today. Seems my friend did something wrong with installing or something. If so I'll keep you posted :)
