### ISSUE TITLE
Incompatible Mod Set

### ISSUE THREAD

**Issue by Sundurr** [MoriyaShiine/enchancement#44]
### Mod version

1.18-18

### A description of the issue

**I have the necessary mods downloaded and in my file and still get this message from fabric.**
------
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install bookshelf, version 13.0.13 or later.
	 - Install enchdesc, version 10.0.2 or later.
Unmet dependency listing:
	 - Mod 'Enchancement' (enchancement) 1.18-18 requires version 13.0.13 or later of bookshelf, which is missing!
	 - Mod 'Enchancement' (enchancement) 1.18-18 requires version 10.0.2 or later of enchdesc, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MoriyaShiine** [comment]
You need to install the mods it's asking for. You can find them under each file on the CurseForge page
