### ISSUE TITLE
multiplayer error

### ISSUE THREAD

**Issue by Your0wallet** [MoriyaShiine/enchancement#45]
### Mod version

fabric 1.19

### A description of the issue

![image](https://user-images.githubusercontent.com/110318206/184465648-b5eb9c1b-c436-4276-aa58-ff15cef6a0de.png)
Ive been having this issue and i dont know how to fix it and it only happens in multiplayer though

**Comment by MoriyaShiine** [comment]
Client and server need to have the same config
