### ISSUE TITLE
overhaulEnchantingTable option (possible) bug

### ISSUE THREAD

**Issue by Nekkok** [MoriyaShiine/enchancement#48]
### Mod version

enchancement-1.19-4

### A description of the issue

I'm a terrible person, I just want to use some of your enchantments and use the allowedEnchantments option to disable some of the vanilla ones. So when I disable the rest of the options and leave these two active, the vanilla enchanting table only shows a few ones and none of enchancement. The logs don't show nothing wrong with the mod, as the game works smooth, so I thought this was a bug, just as it was created to work the overhaul of the enchanting table.

**Comment by kxkxrxtx** [comment]
Here's the [enchancement.json](https://gist.github.com/kxkxrxtx/e8176cf91c0bb8665f58dd9ff3c43e32)
Here's the [latest.log](https://github.com/MoriyaShiine/enchancement/files/9339358/latest.log)
And here are [some screenshots](https://imgur.com/a/3bfccMH) to understand it better.

**Comment by MoriyaShiine** [comment]
This is "intended" behavior; all of the Enchancement enchantments need level 20 (more bookshelves) to show up in the table. The slots being empty is just what Minecraft does when it can't find anything
