### ISSUE TITLE
Items are unbreakable with this mod on qfapi-4.0.0-beta.9_qsl-3.0.0-beta.14_fapi-0.60.0_mc-1.19.2

### ISSUE THREAD

**Issue by lospejos** [MoriyaShiine/enchancement#49]
### Mod version

1.19-4

### A description of the issue

1) Have installed mods:
1.1) `qfapi-4.0.0-beta.9_qsl-3.0.0-beta.14_fapi-0.60.0_mc-1.19.2`
1.2) `enchancement-1.19-4`
1.3) `Bookshelf-Fabric-1.19.1-15.0.1`
1.4) `EnchantmentDescriptions-Fabric-1.19.1-12.0.1`
1.5) `modmenu-4.0.6`
1.6) `tooltipfix-1.0.5-1.19`
2) Created a new world;
3) No error nor crash, but every item became unbreakable (axe, pickaxe etc), but I expected they will have normal durability reducing while they are used.

Please assist.

**Comment by devilmcYT** [comment]
The mod is meant to have no durability if u want to disable it u have to configure the mod

**Comment by lospejos** [comment]
OK, sorry for my issue, closing it. Thanks!
