### ISSUE TITLE
Shovel w/ Bury Enchant Still applies to hotbar slot after Shovel has been dropped

### ISSUE THREAD

**Issue by Kebikyu** [MoriyaShiine/enchancement#56]
### Mod version

1.18-18

### A description of the issue

DISCLAIMER: Bugs I find may not be the sole responsibility of the mod I make the bug-reports for, since I find them on modpack servers.

A Shovel with the Bury enchancement, when dropped, does not remove the enchancement from the now empty hotbar slot. The empty hotbar slot still functions in the same way the shovel does, with the same disable timer as the shovel. The hotbar slot remains this way until a new item is moved to it, it is filled by picking up an item, or the player closes the session.

**Comment by MoriyaShiine** [comment]
I am unable to reproduce this. Can you see if this still happens on 1.19-4 with no other mods?
