### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by AnomalousDeity** [MoriyaShiine/enchancement#59]
### Mod version

1.19-4

### A description of the issue

I have the config set to have single enchantment mode off.. yet when i enchant anything i cant put the item back into the table. 
Unless im misunderstanding how the mod/config works.

Yes i have other mods as well and its modpack sized, this is the only mod that changes how enchanting works, the rest only add new enchants or edit max levels of enchants.

**Comment by MoriyaShiine** [comment]
Expected behavior; you need to use a grindstone (or some other method) to remove the enchantment(s) before you can put it back in regardless of single enchantment mode, just like vanilla
