### ISSUE TITLE
Quilt usage

### ISSUE THREAD

**Issue by choiceofwords5** [MoriyaShiine/enchancement#60]
### Mod version

1.19-4

### A description of the issue

When I try to use this mod on quilt with qsl and qfapi I can’t load the game is this possible to fix or is it just not built for quilt?

pls help,

ChoiceOfWords5

just in case the other mods I were using were

canvas
Impaled
Blast 
Pick your poison
Illuminations
Mason decor 
Rats mischief
Geckolib
Requiem 
Requiem pandemonium expansion

Thanks again,

choice of words 5

**Comment by MoriyaShiine** [comment]
It should work fine on quilt; please send a log file

**Comment by Puffadillo** [comment]
It works fine on Quilt for me. It's one of your other mods but no one can help without a log.

**Comment by choiceofwords5** [comment]
Yeah I figured it out thanks guys I needed more dependencies than normal:

tooltipfix
Enchantment descriptions and bookshelf libraries
