### ISSUE TITLE
Issue with re-implementing almost all vanilla enchants

### ISSUE THREAD

**Issue by RedPanda483** [MoriyaShiine/enchancement#62]
### Mod version

1.19-4

### A description of the issue

I have tried to re-implement most of the minecraft enchants but it is not working i have edited the .json file but It isn't working. have i missed anything?
![image](https://user-images.githubusercontent.com/113170573/193506952-2b416478-3f0c-4d2a-a37b-9ca833bed793.png)
All are marked as "Fire Aspect . . . ?" in the enchant table image.
Gist for the .json
https://gist.github.com/RedPanda483/ac97b88530f4cfd6bbb65ebbac262515

**Comment by MoriyaShiine** [comment]
Uh

Do you have some other mod interfering with the Enchanting Table? You have overhaulEnchantingTable set to true but nothing has changed

**Comment by RedPanda483** [comment]
ill try to send my mods folder as a zip

**Comment by RedPanda483** [comment]
too big

**Comment by MoriyaShiine** [comment]
Don't send me your mods folder lol

Send a log, and try removing mods until it starts working like intended

**Comment by RedPanda483** [comment]
oh oop, ill try sending that just in case there is an incompatible mod, it was fine with all the mods though untill I changed the config file

**Comment by RedPanda483** [comment]
here is a google drive link to the zip https://drive.google.com/file/d/16nf5RZAW7KYDy7ned_0SyHSKh5J4IqDZ/view?usp=sharing

**Comment by RedPanda483** [comment]
ill try the removing mods now

**Comment by RedPanda483** [comment]
oh and also I cant /enchant or find any of the enchant books I added back

**Comment by RedPanda483** [comment]
can you plz send the original config and I will see if it works with that

**Comment by MoriyaShiine** [comment]
Delete the file and it'll regenerate with default values

And please stop sending so many comments, I get an email for every single one. Joining the discord would be a lot easier

**Comment by RedPanda483** [comment]
oh ok sorry, i removed rangers heaven it it isnt working still so its the config i think
