### ISSUE TITLE
Lumberjack

### ISSUE THREAD

**Issue by dumpyman** [MoriyaShiine/enchancement#63]
### Mod version

Most latest

### A description of the issue

Is there anyway to use lumberjack on non-vanilla trees? if not is it possible for you guys to add Oh the Biomes trees to be compatible for lumberjack

**Comment by MoriyaShiine** [comment]
It already works on modded trees; either see if the tree is too big (you can increase the maximum size from 1024 in the config) or report to BYG that they're missing logs in the minecraft:logs tag

**Comment by dumpyman** [comment]
wierd, placed logs work but not planted ones

**Comment by MoriyaShiine** [comment]
Check the horizontal length limit in the config, the tree may be too big
