### ISSUE TITLE
Enchancement is causing the log file to fill up with armor spam

### ISSUE THREAD

**Issue by itzacookie** [MoriyaShiine/enchancement#69]
### Mod version

1.19-7

### A description of the issue

 The server and client both receive messages spamming " Couldn't set damage of loot item 1 (insert vanilla armor)" over and over with each vanilla armor item, and it causes server lag to where it cannot be played.  Client side it only causes minor lag and is playable but i am trying maker a server for it.  I am not sure why it is causing this but I think it may be config related? Any help would be appreciated.

### Log or crash report

https://gist.github.com/itzacookie/acd889721c24fc320472179596cee581#file-latest-log

**Comment by MoriyaShiine** [comment]
I don't see this anywhere in the log, but I guess try removing mods to see what causes it?

**Comment by itzacookie** [comment]
thank you for the fast reply.  It senmt the wrong log im not sure why.  I have been for hours and im gonna for a little longer.  
[2022-12-03-4.log](https://github.com/MoriyaShiine/enchancement/files/10147343/2022-12-03-4.log)

**Comment by MoriyaShiine** [comment]
Odd. Are you sure it's Enchancement? I don't set damage anywhere in the mod, especially during loot loading

**Comment by itzacookie** [comment]
yeah I am I'm not sure why but when I remove just enchancement it stops.  Here is the log with me running the exact same mod pack but without enchancement.  I think another mod is messing with the values or something because if i launce enchancement alone with no other mods it runs fine.  Coming here was kind of like a last resort
[latest.log](https://github.com/MoriyaShiine/enchancement/files/10147359/latest.log)

**Comment by MoriyaShiine** [comment]
I guess start removing mods until you find what causes it in conjunction with Enchancement, unfortunately

**Comment by itzacookie** [comment]
alright thank you for your time anyways man.  I will let you know what mod it is if i find it :)
