### ISSUE TITLE
Unable to add compatibility for BCLib ores

### ISSUE THREAD

**Issue by SplendidAlakey** [MoriyaShiine/enchancement#70]
### Mod version

1.19-7

### A description of the issue

I made a datapack to make Extracting enchantment work with [BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib) mods' ores, based on the pinned example from Discord, adding modded ores from [BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether) and [BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend), but none worked. The datapack itself works, because I tried it with another mod, Expanded Delight, which worked perfectly file. So it has something to do with BCLib mods specifically.

Here's the pack: [test.zip](https://github.com/MoriyaShiine/enchancement/files/10180052/test.zip)

### Log or crash report

https://gist.github.com/SplendidAlakey/19350f45302bffb6966dd37c4a50f30f

**Comment by MoriyaShiine** [comment]
Ores also need to be in the c:ores tag (the general ores tag) in order for extracting to pick up on it. I've attached a fixed datapack, but I suggest asking the devs of BetterNether and BetterEnd to add their blocks to that tag.

[ores.zip](https://github.com/MoriyaShiine/enchancement/files/10180163/ores.zip)

**Comment by SplendidAlakey** [comment]
Apologies for a delayed response. The fixed version of the datapack also doesn't work. But I don't believe this is the issue with your mod, anyway, because I checked with F3+H and the tags were absent, despite the datapack being active. KubeJS does add the tag, on the other hand, but something still goes wrong. I suspect BCLib mods will have to add it natively.

Thanks for the reply, though, and sorry for wasting your time!
