### ISSUE TITLE
Returning durability to items

### ISSUE THREAD

**Issue by GameOnne** [MoriyaShiine/enchancement#71]
### Mod version

1.19-7

### A description of the issue

So I've recently ran into a mod compatibility issue, and to fix it I have to return durability to an item. I've noticed the tag (enchancement:retains_durability), yet no matter what I do it looks like the tag doesn't get applied. There are no solutions on the internet. How can I apply the tag properly?

**Comment by MoriyaShiine** [comment]
Are you sure you're applying the datapack? Here's a test datapack that enables durability for diamond pickaxes that you can add/remove to/from.
[durabilitytest.zip](https://github.com/MoriyaShiine/enchancement/files/10195372/durabilitytest.zip)

**Comment by GameOnne** [comment]
It works. Turns out I was simply an idiot and confused the folders' order. Thanks a lot!
