### ISSUE TITLE
I backported many fixes from 1.19 back to 1.18. Cannot make PR to a new branch

### ISSUE THREAD

**Issue by rockbyo5** [MoriyaShiine/enchancement#72]
### Mod version

1.18-19

### A description of the issue

Everything is in the title.

Link to repository with a 1.18 branch: 
https://github.com/rockbyo5/enchancement

**Comment by MoriyaShiine** [comment]
I don't usually update my mods for older versions. Enough has changed that I *might* go back and backport, but there's no guarantee

**Comment by rockbyo5** [comment]
Thanks for updating the 1.18 version with the fixes!
I had been using my own build since i needed some of the fixes myself, but i highly appreciate when mod authors can provide some level of support (especially important bug fixes) to older Minecraft versions, since otherwise, many modpack users are stuck with bugs that are either hard or impossible to fix without food programming knowledge and access to the source code.

You don't have to do it, but it would be a great help if you could keep branches for old versions, regardless of whether or not you actually commit anything to them. This would allow other developers like myself to contribute/backport fixes more easily, and it would honestly not add much work for you when upgrading to a new Minecraft version (It's basically 3-6 clicks and then you forget it).
In the end, I'm glad you took the time to do this at all, so thank you!
