### ISSUE TITLE
durability can't be enabled!

### ISSUE THREAD

**Issue by shupliance** [MoriyaShiine/enchancement#77]
### Mod version

1.19-8, 1.19-9

### A description of the issue

durability cannot be turned on! i'm not quite sure how to give you more information, there's no crashlog to give because there's no crash, simply put, nothing changes when I turn unbreakingChangesFlag to 1, or -1.

**Comment by MoriyaShiine** [comment]
Are you on a server? If so, make sure both the client and the server have the same setting

**Comment by shupliance** [comment]
> n

I was indeed on a server, upon turning both to 1 it synced up, but does every player on my server now have to do this?

**Comment by shupliance** [comment]
I was indeed on a server, upon turning both to 1 it synced up, but does every player on my server now have to do this?

**Comment by MoriyaShiine** [comment]
Yes, config files should always be synced regardless of mod
