### ISSUE TITLE
Extracting Enchantment is Incompatible With Non-Traditional Ores

### ISSUE THREAD

**Issue by Noobulus** [MoriyaShiine/enchancement#79]
### Mod version

1.19-10

### A description of the issue

[Spelunkery](https://modrinth.com/mod/spelunkery) adds several new ores that don't have Stone or Deepslate as their 'base' stone. As such, they don't work properly with extracting and simply break like regular blocks.

The ores in question are: Calcite Redstone Ore, Sandstone Lapis Ore, Andesite Emerald Ore, and Smooth Basalt Diamond Ore.

**Comment by Fourbo** [comment]
Maybe a whitelist could be added to the config where block ids could be manually added? And mod compatibility could be included with several popular mods that automatically populate the list when they are detected.

**Comment by cph101** [comment]
This should be possible using tags. @MoriyaShiine might have already implemented this in the recent push but I haven’t looked at it extensively. I’ll check again, and I might provide a (probably very scuffed) fix for this next week.
