### ISSUE TITLE
Turning off "Overhaul Enchanting Table" config generates enchantment options which cannot be selected

### ISSUE THREAD

**Issue by DanielJWhittaker** [MoriyaShiine/enchancement#8]
### Mod version

v1.18-15

### A description of the issue

Title. Efficiency is a common selectable enchantment at low levels, and at higher levels, you can still see ones like Slide, Perception, or Fire Aspect, but amongst a bunch of unselectable enchantments which do not render any enchantment name when hovering above them for the preview. Could be intentional tbh but figured I'd mention it because this is like the only mod I've ever seen to overhaul enchanting in exactly the way I would like it
![image](https://user-images.githubusercontent.com/58282249/169196958-f2e4b147-a81a-4e93-b66c-02d081d68a8b.png)

**Comment by MoriyaShiine** [comment]
This isn't _exactly_ intentional but is expected. With only a few enchantments to pick from, the table will most of the time just not have anything; this is fixed by enabling the vanilla enchantments but of course that may not be what you're looking for. I could try to force at least one to show up if that's a solution you'd want

**Comment by DanielJWhittaker** [comment]
> This isn't _exactly_ intentional but is expected. With only a few enchantments to pick from, the table will most of the time just not have anything; this is fixed by enabling the vanilla enchantments but of course that may not be what you're looking for. I could try to force at least one to show up if that's a solution you'd want

I think forcing at least 1 would prevent certain equipment from locking and forcing you to add a dummy enchant to like a book or something. Other question I had since I have you here, how do I go about adding vanilla enchants back in, like say if I wanted to add Fortune and Looting back in? I tried simply appending them to the enchant whitelist but maybe I missed something.

**Comment by MoriyaShiine** [comment]
You just have to add them to the allowed enchantments list (inverted is an option too, emptying the list and setting inverted to true will allow all enchantments). You'll need to restart the game in either case since the enchantment registry is frozen on game load

**Comment by DanielJWhittaker** [comment]
> You just have to add them to the allowed enchantments list (inverted is an option too, emptying the list and setting inverted to true will allow all enchantments). You'll need to restart the game in either case since the enchantment registry is frozen on game load

Ah, gotcha, I didn't restart since every config I fiddled with up until that point didn't require it so I assumed it didn't. Thanks for all the help! I really do love this version of enchanting, so that every item actually feels magical instead of braindead "optimal strategy" Protection IV, Power V, Unbreaking Mending yadda yadda

**Comment by MoriyaShiine** [comment]
Yep, it's marked as requires restart but I'm not sure why mod menu ignores it. Glad you like it though!

**Comment by DanielJWhittaker** [comment]
> Yep, it's marked as requires restart but I'm not sure why mod menu ignores it. Glad you like it though!

Oh yeah, one last question, why is the Unbreaking Changes Flag a number entry instead of a boolean? Is there a 3rd durability mode?

**Comment by DanielJWhittaker** [comment]
> > Yep, it's marked as requires restart but I'm not sure why mod menu ignores it. Glad you like it though!
> 
> Oh yeah, one last question, why is the Unbreaking Changes Flag a number entry instead of a boolean? Is there a 3rd durability mode?

Ah, I found it on the modpage, I thought I did:
"Everything in the mod is also configurable down to disabling the entire mod if there are features that you wish to disable. All of the config options are self explanatory except for unbreakingChangesFlag (0 means all items are unbreakable, greater than 0 means items with x level of Unbreaking are unbreakable, and less than 0 means disabled)."

**Comment by MoriyaShiine** [comment]
It's the only unintuitive option, I explain it in the curseforge page; 0 means all tools, >0 means you need x level of unbreaking, <0 means never

**Comment by MoriyaShiine** [comment]
Sorry for taking so long to end up fixing this! It's not a very elegant solution (unchoosable enchantments will all be the first found in the registry) but it works for now lol
