### ISSUE TITLE
Incompatible with Bookshelf 16.2.17

### ISSUE THREAD

**Issue by Sunconure11** [MoriyaShiine/enchancement#80]
### Mod version

1.19.10

### A description of the issue

Mod crashes with said build of bookshelf. That is all there is to be said.

### Log or crash report

https://gist.github.com/Sunconure11/530ea6fb740cae6a13cbfa1a5ccae47e

**Comment by MoriyaShiine** [comment]
I must have accidentally hardcoded the version requirement for 1.19.2. Either downgrade or use a dependency override and I'll fix it next version

**Comment by MoriyaShiine** [comment]
Fixed as of 1.19-12
