### ISSUE TITLE
Pick your poison crashes when I use it with enchancement

### ISSUE THREAD

**Issue by abdoman91** [MoriyaShiine/enchancement#81]
### Mod version

1.18-17

### A description of the issue

Starting the game crashes instantly with the following crash report

(I know this issue doesn't happen on the latest version I just want to know if there is a way to fix it and still use 1.18.2)

### Log or crash report

https://gist.github.com/abdoman91/6c8be2c948294cf157a4d55e9784db64

**Comment by ItsStyx** [comment]
I have this issue as well.

**Comment by MoriyaShiine** [comment]
Either downgrade Geckolib (unsure which version, but I know some older ones work) or update to 1.19. Unfortunately, 1.18 no longer receives updates
