### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by NotCeph** [MoriyaShiine/enchancement#84]
### Mod version

1.19.2

### A description of the issue

Server crashes randomly, be it just as we join on 30 minutes to an hour of play, no particular action seems to trigger the crash, it just happens.

### Log or crash report

https://gist.github.com/NotCeph/8efd75c90eb85b3abb88add6aec089e4

**Comment by MoriyaShiine** [comment]
Clone of #83

Update to 1.19-14
