### ISSUE TITLE
Crash while hovering mouse on enchants

### ISSUE THREAD

**Issue by adrakusek** [MoriyaShiine/enchancement#87]
### Mod version

1.19-5

### A description of the issue

When i hover on any button in enchanting table my game instantly crashes.
Im on the newest 1.19 version and i dont really want to move to newer ones due to personal reasons
I also got the newest dependencies

### Log or crash report

https://gist.github.com/adrakusek/168a0ed8a85f50d3dfbe282d4642a0b8

**Comment by MoriyaShiine** [comment]
Already fixed in newer versions. If you don't want to update then my only suggestion is downgrade tooltipfix, but I _highly_ suggest updating since you're missing out on many bugfixes and additions
