### ISSUE TITLE
Change the ore registry to use conventional block tags instead of just "c:ores"

### ISSUE THREAD

**Issue by Desempregago** [MoriyaShiine/enchancement#9]
### Mod version

v1.18-15

### A description of the issue

This will *probably* make Extracting work with every ore that has a valid tag

**Comment by MoriyaShiine** [comment]
I'm not sure what you mean by this, if a mod doesn't add its ores to the common block tag then I can't really do anything about that

**Comment by MoriyaShiine** [comment]
I've moved to conventional block tags, but it's functionally identical; other mods will have to use it too, as the tag is still c:ores
