### ISSUE TITLE
unable to join world

### ISSUE THREAD

**Issue by nuelhgw** [MoriyaShiine/enchancement#90]
[2023-04-05-5.log](https://github.com/MoriyaShiine/enchancement/files/11172041/2023-04-05-5.log)
### Mod version

1.19.4

### A description of the issue

whenever i try to join a world after the chunk loading animation is in 100% nothing happens again i disable every single mod that i had and only enabled mod menu plus the enchantment mod and it dependency i even disabled texture packs i can't join worlds and it not like the game is not responding or anything it not just working

**Comment by MoriyaShiine** [comment]
fixed as of https://github.com/MoriyaShiine/enchancement/pull/91
