### ISSUE TITLE
Registry remapping failed

### ISSUE THREAD

**Issue by Zapzidus** [MoriyaShiine/enchancement#93]
### Mod version

enchancement-1.19-18.jar

### A description of the issue

![Screenshot 2023-04-11 154704](https://user-images.githubusercontent.com/102423069/231272531-9861d6e1-86b6-412d-9644-d91bcd289961.png)
When I tried to put enchancement into my Fabric Minecraft server but I was met with this every time I tried to join. How can I fix this?
the Server Hosting I use is PebbleHost

**Comment by MoriyaShiine** [comment]
Both your client and server configs need to match
