### ISSUE TITLE
bringing back vanilla enchantments

### ISSUE THREAD

**Issue by technikfratnik23** [MoriyaShiine/enchancement#97]
### Mod version

1.19-14

### A description of the issue

So when I set invertedList to true, whenever I join my server (not singleplayer) I get the "Registry remapping failed: Received ID map for minecraft:enchantment contains IDs unknown to the receiver!" and lists every a bunch of vanilla enchantments even after customizing the config on the client and copying it to the server the same error removing everything in allowedEnchantments both client and server doesn't help. And I can't use newer version because I'm running on 1.19.2
[cfg.zip](https://github.com/MoriyaShiine/enchancement/files/11347759/cfg.zip)

**Comment by MoriyaShiine** [comment]
Having matching config files should work. Are you sure it copied properly?

**Comment by technikfratnik23** [comment]
> Having matching config files should work. Are you sure it copied properly?

Yeah, I'm doing select all and copy so should work, but it doesn't. Setting invertedList to true fixes the registry remapping

**Comment by MoriyaShiine** [comment]
Send both your client and server config files

**Comment by technikfratnik23** [comment]
[configs.zip](https://github.com/MoriyaShiine/enchancement/files/11348007/configs.zip)
And now i'm getting "Registry remapping failed: Failed to assign new id to client only registry entry"

**Comment by MoriyaShiine** [comment]
Configs look the same, does the client and server have the same mod version?

**Comment by technikfratnik23** [comment]
[logs.zip](https://github.com/MoriyaShiine/enchancement/files/11348115/logs.zip)

**Comment by MoriyaShiine** [comment]
The server's enchantment registry is empty, did you make sure to edit the config while the server is offline?

**Comment by technikfratnik23** [comment]
yeah i've edited it while the server is offline

**Comment by MoriyaShiine** [comment]
There's no reason it shouldn't work then. Try reinstalling all mods and making sure they match?
