### ISSUE TITLE
Does this really need tooltipfix? Makes it incompatible with adaptive tooltips on 1.19.2

### ISSUE THREAD

**Issue by Chris-Creates** [MoriyaShiine/enchancement#99]
### Mod version

1.19-14

### A description of the issue

It's listed as dependency and I cant find a way to try running without tooltipfix.

**Comment by MoriyaShiine** [comment]
It's not *strictly* required, but tooltips become unreadable without it. If adaptive tooltips also does this, you can use a dependency override https://fabricmc.net/wiki/tutorial:dependency_overrides

**Comment by Chris-Creates** [comment]
thank you! and yeah adaptive also does that plus more.
